# Generated by Django 2.0.1 on 2018-01-25 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bracket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Seed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.SmallIntegerField()),
                ('id_bracket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Bracket')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('num_brackets', models.SmallIntegerField()),
                ('num_bracket_seeds', models.SmallIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='bracket',
            name='id_tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Tournament'),
        ),
        migrations.AlterUniqueTogether(
            name='seed',
            unique_together={('id_bracket', 'name', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='bracket',
            unique_together={('id_tournament', 'name')},
        ),
    ]
