# Generated by Django 2.0.1 on 2018-01-25 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bracket',
            old_name='id_tournament',
            new_name='tournament',
        ),
        migrations.RenameField(
            model_name='seed',
            old_name='id_bracket',
            new_name='bracket',
        ),
        migrations.AlterUniqueTogether(
            name='bracket',
            unique_together={('tournament', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='seed',
            unique_together={('bracket', 'name', 'value')},
        ),
    ]
